config/routes.rb
Rails.application.routes.draw do

  resources :posts
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end



resources :tutorials

get '/' => 'pages#index'
get '/home' => 'pages#index'

# Learn and tutorials
get '/learn' => 'tutorials#learn'
get '/seeadmin' => 'adminpages#seeadmin'
get '/posts_admin' => 'adminpages#posts_admin'

# Compete
get '/compete' => 'pages#compete'

get '/sell' => 'pages#sell'

get '/social' => 'pages#social'

get '/sounds' => 'pages#sounds'

get '/test' => 'pages#test'

get '/postlist' => 'posts#postlist'

get '/myposts' => 'posts#myposts'

get 'testing' => 'posts#testing'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
# validates :title, :description, :audio, presence: true

  has_one_attached :audio
  belongs_to :user
  has_many :comments
  acts_as_votable

  def score
    self.get_upvotes.size - self.get_downvotes.size
  end
  
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :posts
has_many :comments

end

app/controllers/adminpages_controller.rb
class AdminpagesController < ApplicationController
  before_action :set_tutorial, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action do
    redirect_to new_user_session_path unless current_user && current_user.admin?
  end

  def seeadmin
    @tutorials = Tutorial.all
    @tutorial = Tutorial.new
  end

  def posts_admin
    @posts = Post.all
    @post = Post.new
  end

  private

  def auth_admin!
    redirect_to new_user_session_path unless current_user && current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def compete
  end

  def sell
  end

  def social
  end

  def sounds
  end

  def test
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # before_action :auth_admin!, only: [:show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: posts_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def postlist
    @posts = Post.all
    @users= User.all
  end

  def myposts
    @posts = Post.all
  end

  def testing
    @posts = Post.all
  end


  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
     redirect_back fallback_location: posts_path
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
     redirect_back fallback_location: posts_path
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :audio, :user)
    end

    def auth_admin!
      redirect_to new_user_session_path unless current_user && current_user.admin?
    end

end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_action :set_tutorial, only: [:show, :edit, :update, :destroy]

def react
  @tutorials = Tutorial.all
end


def trythis
  @tutorials = Tutorial.all
end

def learn
  @tutorials = Tutorial.all
end

# GET /tutorials
# GET /tutorials.json
  def index
    @tutorials = Tutorial.all

    respond_to do |format|
      format.html
      format.json do
        render json: @tutorials
    end
  end
end

# GET /tutorials/1
# GET /tutorials/1.json
  def show
  end

  # GET /tutorials/new
  def new
    @tutorial = Tutorial.new
    @tutorials = Tutorial.all
  end

# GET /tutorials/1/edit
  def edit

  end

# POST /tutorials
# POST /tutorials.json
  def create
    @tutorials = Tutorial.all
    @tutorial = Tutorial.new(tutorial_params)

      if @tutorial.save
        render json: @tutorial
      else
        render json: @tutorial.errors.full_messages, status:400
      end
  end

# PATCH/PUT /tutorials/1
# PATCH/PUT /tutorials/1.json
  def update
    respond_to do |format|
      if @tutorial.update(tutorial_params)
        format.html { redirect_to @tutorial, notice: "Tutorial was successfully updated."}
        format.json {render :show, status: ok, location: @tutorial}
      else
        format.html { render :edit }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity}
      end
    end
  end

# DELETE /tutorials/1
# DELETE  /tutorials/1.json
  def destroy
    @tutorial = Tutorial.find(params[:id])
    @tutorial.destroy
    render json: @tutorial
  end

# admin view
  def admin
    @tutorials = Tutorial.all
  end

private
 # Use callbacks to share common setup or constraints between actions.

 def set_tutorial
   @tutorial = Tutorial.find(params[:id])
 end

#don't trust
def tutorial_params
  params.require(:tutorial).permit(:name,:description,:link)
  # params.require(:tutorial).permit(:description)
end

end

app/helpers/adminpages_helper.rb
module AdminpagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/adminpages/posts_admin.html.erb
<p id="notice"><%= notice %></p>

<h3>Admin View - The Lab</h3>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= User.find(post.user_id).email %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/adminpages/seeadmin.html.erb
<%= react_component "Seeadmin" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beat Making Lab</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= javascript_pack_tag 'Everything' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!-- Import materialize.css -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css" rel="stylesheet">

        <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>

  </head>


  <body>
    <%= react_component 'App', props: { route: request.path, user: current_user, adminvalue: current_user.try(:admin?), userlogin: user_signed_in? } %>
    <%= yield %>
  </body>
  
</html>

app/views/pages/compete.html.erb
<%= react_component 'Compete' %>

app/views/pages/index.html.erb
<%= react_component 'Home' %>

app/views/pages/sell.html.erb
<%= react_component 'Sell' %>

app/views/pages/social.html.erb
<%= react_component 'Social' %>

app/views/pages/sounds.html.erb
<%= react_component 'Sounds' %>

app/views/pages/test.html.erb
<h3>test</h3>

<%= form.file_field :attachments, multiple: true, direct_upload: true %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>


  <div class="field">
  <%= form.label :user %>
  <%= current_user.email %>
  <%= current_user.id %>
  </div>

  <div class="field">
  <%= form.label :audio %>
  <%= form.file_field :audio %>
</div>


  <div class="actions">
    <%= form.submit %>
  </div>



<% end %>

app/views/posts/edit.html.erb
<h3>Editing Post</h3>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<a href="/myposts">Back to my posts</a>

<% if current_user.try(:admin?) %>
| <%= link_to 'Back to All Posts', posts_path %>
<% end %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Admin View - The Lab Posts</h3>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user_id %></td>
        <td><%= post.score %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to "upvote", like_post_path(post), method: :put %></td>
        <td><%= link_to "downvote", dislike_post_path(post), method: :put %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/myposts.html.erb
<div class="post lab2">
<h3 class="headerText">MY LAB</h3>

<h5><p class="headerText">This is where you can see and edit all the posts you've made to the Lab!</p></h5>

<% if user_signed_in? %>
<span id=>
<a href="/posts/new"><button>New post</button></a>
</span>
<% end %>

<% @posts.order("created_at DESC").each do |post| %>

<!-- not very scalable... -->
<% if post.user_id === current_user.id %>

  <div class="micropost">

    Uploaded by: <%= User.find(post.user_id).email %><br/>
    <%= post.created_at.strftime("%B %e, %Y (%m:%M %p )") %><br/>

    <!-- remove title if there isn't any -->
    <% if post.title != "" %>
    Title: <%= post.title %><br/>
    <%end%>

    <!-- remove description if there isn't any -->
    <% if post.content != "" %>
    <blockquote><%= post.content %></blockquote>
    <%end%>

    <!-- If something is attached, let you download it -->
    <% if post.audio.attached? %>
    <audio controls>
        <source src="<%= url_for(post.audio) %>" type="audio/mp3">
    </audio>
    <p><a href="<%= url_for(post.audio) %>">DOWNLOAD</a></p>
    <%end%>

<!-- Show the controls for your own post -->
  <%= link_to 'Show', post %>
  <%= link_to 'Edit', edit_post_path(post) %>
  <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>


<!-- Conditional for upvote -->
  <div class="voting"><%= post.score %>
  <% if post.score > -1 %>
  💖
  <% else %>
  💔
  <% end %>

  <!-- Upvote/downvote arrows -->
  <%= link_to "⬆️", like_post_path(post), method: :put %> |
  <%= link_to "⬇️", dislike_post_path(post), method: :put %>
  </div>

</div>
<% end %>

<% end %>
</div>

app/views/posts/new.html.erb
<h3>New Post</h3>

<%= @post.user %>

<%= render 'form', post: @post %>

<a href="/myposts">Back to my posts</a>

<% if current_user.try(:admin?) %>
| <%= link_to 'Back to All Posts', posts_path %>
<% end %>

app/views/posts/postlist.html.erb
<div class="post lab">
<h3 class="headerText">THE LAB</h3>



<h5><p class="headerText">Welcome to the Lab! This is a space for everyone to share snippets of the sounds they're working on.
  If you like someone else's sound, feel free to download it or show them some love! Experimentation, as always, is highly encouraged!</p></h5>


<% if user_signed_in? %>
<span id=>
<a href="/posts/new"><button>New post</button></a>
</span>
<% end %>

<% @posts.order("created_at DESC").each do |post| %>

  <div class="micropost">

  Uploaded by: <%= User.find(post.user_id).email %><br/>
  <%= post.created_at.strftime("%B %e, %Y (%m:%M %p )") %><br/>
  <% if post.title != "" %>
  Title: <%= post.title %><br/>
  <%end%>
  <!-- remove description if it there isn't any -->
  <% if post.content != "" %>
  <blockquote><%= post.content %></blockquote>
  <%end%>
  <!-- If something is attached, let you download it -->

  <% if post.audio.attached? %>
  <audio controls>
      <source src="<%= url_for(post.audio) %>" type="audio/mp3">
  </audio>
  <p><a href="<%= url_for(post.audio) %>">DOWNLOAD</a></p>
  <%end%>

  <!-- Show the controls for your own post -->
  <% if user_signed_in? && post.user_id === current_user.id %>
  <%= link_to 'Edit', edit_post_path(post) %>
  <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>

  <!-- Conditional for upvote -->

    <div class="voting"><%= post.score %>
    <% if post.score > -1 %>
    💖
    <% else %>
    💔
    <% end %>

    <!-- Upvote/downvote arrows -->
    <%= link_to "⬆️", like_post_path(post), method: :put %> |
    <%= link_to "⬇️", dislike_post_path(post), method: :put %>
    </div>
  </div>

<% end %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<% if @post.audio.attached? %>
<!-- @post.audio.present? will always return true, use attached? to check presence -->
  <p>
    <strong>audio:</strong>
    <br>
    <%= audio_tag(url_for(@post.audio)) %>

<audio controls>
    <source src="<%= url_for(@post.audio) %>" type="audio/mp3">
</audio>
        <%#= @post.audio %>

  </p>
<% end %>


<%= link_to 'Edit', edit_post_path(@post) %> |
<a href="/myposts">Back to my posts</a>

<% if current_user.try(:admin?) %>
| <%= link_to 'Back to All Posts', posts_path %>
<% end %>

app/views/posts/testing.html.erb
 <div class="post lab">
 <h3 class="headerText">THE LAB</h3>

 <h5><p class="headerText">Welcome to the Lab! This is a space for everyone to share snippets of the sounds they're working on.
   If you like someone else's sound, feel free to download it or show them some love! Experimentation, as always, is highly encouraged!</p></h5>

 <%= link_to 'New Post', new_post_path %>

 <% post = @posts.last %>

   <div class="micropost">

     <% waveform = AudioWaveform::WaveformDataFile.new(filename: "http://localhost:3000/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--21f4f71cb8a0a2905fab4391ca97224eda143179/bless%20up.mp3")%>

     <%= waveform.sample_rate %>




   Uploaded by: <%= User.find(post.user_id).email %><br/>
   <%= post.created_at.strftime("%B %e, %Y (%m:%M %p )") %><br/>
   <% if post.title != "" %>
   Title: <%= post.title %><br/>
   <%end%>
   <!-- remove description if it there isn't any -->
   <% if post.content != "" %>
   <blockquote><%= post.content %></blockquote>
   <%end%>
   <!-- If something is attached, let you download it -->

   <% if post.audio.attached? %>
   <audio controls>
       <source src="<%= url_for(post.audio) %>" type="audio/mp3">
   </audio>
   <p><a href="<%= url_for(post.audio) %>">DOWNLOAD</a></p>
   <%end%>

   <!-- Show the controls for your own post -->
   <% if user_signed_in? && post.user_id === current_user.id %>
   <%= link_to 'Edit', edit_post_path(post) %>
   <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
   <% end %>

   <!-- Conditional for upvote -->

     <div class="voting"><%= post.score %>
     <% if post.score > -1 %>
     💖
     <% else %>
     💔
     <% end %>

     <!-- Upvote/downvote arrows -->
     <%= link_to "⬆️", like_post_path(post), method: :put %> |
     <%= link_to "⬇️", dislike_post_path(post), method: :put %>
     </div>
   </div>


 </div>

app/views/tutorials/_form.html.erb
<%= form_with(model: tutorial, local: true) do |form| %>
  <% if tutorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tutorial.errors.count, "error") %> prohibited this tutorial from being saved:</h2>

      <ul>
      <% tutorial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_area :link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>



<% end %>

app/views/tutorials/admin.html.erb
<a href="/tutorials">Tutorials</a>



<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @tutorials.each do |tutorial| %>

  <tr>
    <td><%= tutorial.name%></td>
    <td><%= tutorial.description%></td>
    <td><%= tutorial.link%></td>
    <td><%= link_to 'Edit', edit_tutorial_path(tutorial) %></td>
    <td><%= link_to 'Destroy', tutorial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <%end%>
</table>

<%= link_to 'New Tutorial', new_tutorial_path %>

app/views/tutorials/edit.html.erb
<h3>Editing Tutorial</h3>

<%= render 'form', tutorial: @tutorial %>

<%= link_to 'Show', @tutorial %> |
<%= link_to 'Back', tutorials_path %>

app/views/tutorials/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Tutorials</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tutorials.each do |tutorial| %>
      <tr>
        <td><%= tutorial.name %></td>
        <td><%= tutorial.description %></td>
        <td><%= tutorial.link %></td>
        <td><%= link_to 'Show', tutorial %></td>
        <td><%= link_to 'Edit', edit_tutorial_path(tutorial) %></td>
        <td><%= link_to 'Destroy', tutorial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tutorial', new_tutorial_path %>

app/views/tutorials/learn.html.erb
<div class="learn">
<h3 class="headerText">TUTORIALS</h3>


<h5 class="headerText"><p class="headerText">Check out these tutorials selected for you by Apple Juice Kid! No matter what type of music
software you're looking for or your budget, we've got you covered.</p> </h5>

<% @tutorials.each do |tutorial| %>

<div class="tut">

  <h2><a href="<%=tutorial.link%>"><%=tutorial.name%></a></h2>
  <p><%=tutorial.description%></p>
  <div class="youtube">
    <iframe width="600" height="500"
  src="https://www.youtube.com/embed/<%=tutorial.link.partition("=").last.partition("&").first%>"
  frameborder="0" allow="autoplay; encrypted-media" allowfullscreen>
  </iframe>

  </div>
</div>
<%end%>
</div>

app/views/tutorials/new.html.erb
<h3>New Tutorial</h3>

<%= render 'form', tutorial: @tutorial %>
<% @tutorials.each do |tutorial| %>

<tr>
  <td><%= tutorial.name%></td>
  <td><%= tutorial.description%></td>
  <td><%= tutorial.link%></td>
  <td><%= link_to 'Edit', edit_tutorial_path(tutorial) %></td>
  <td><%= link_to 'Destroy', tutorial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
<%end%>

</table>

<%= link_to 'Back', tutorials_path %>

app/views/tutorials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tutorial.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tutorial.description %>
</p>

<p>
  <strong>Link:</strong>
  <%= @tutorial.link %>
</p>

<%= link_to 'Edit', edit_tutorial_path(@tutorial) %> |
<%= link_to 'Back', tutorials_path %>